# Generated by Django 5.2.4 on 2025-07-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0003_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('edad', models.IntegerField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('materia', models.CharField(max_length=100)),
            ],
        ),
    ]
